
public class InputException {
	int x1;
	int x2;

	public InputException() {
	}
	
	public void setX1(int x1)  {
		this.x1 = x1;
	}
	
	public void setX2(int x2)  {
		this.x2 = x2;
	}
	
	public int sum() {
		return x1 + x2;
	}
}




import java.util.Scanner;

public class TestInputException {

	public static void main(String[] args) {
	
		InputException ex = new InputException();
		int x = 1;
		
		do {       // restart method
		try {
			Scanner input = new Scanner(System.in);
			
			System.out.println("Enter first integer: ");
			ex.setX1(input.nextInt());
			
			System.out.println("Enter second integer: ");
			ex.setX2(input.nextInt());
			
			System.out.print("Sum is: " + ex.sum());
			
			x = 2;
		} 
		catch(Exception e) {
			System.out.println("Invalid input");
		    }
		}
		while (x == 1);
	}	
}
